<?xml version="1.0"?>

<!DOCTYPE AtlantisConfiguration [

<!ELEMENT AtlantisConfiguration (Initialization, Parameters,ParameterDifferences*, WindowCorners*)>

<!ELEMENT Initialization (Interactions, Canvas)>

<!ELEMENT Interactions (Panel*, InteractionControl+)>

<!ELEMENT InteractionControl (Panel*)>
    <!ATTLIST InteractionControl
        projectionName    CDATA #REQUIRED
        availableInDemoMode     CDATA "YES"
        defaultInDemoMode CDATA "NO" >

<!ELEMENT Panel EMPTY>
    <!ATTLIST Panel
        screenName CDATA #REQUIRED
        fileName   CDATA #REQUIRED
        toolTip    CDATA "">

<!ELEMENT Canvas (UsedWindow+, Layout+)>
    <!ATTLIST Canvas
        startupLayout CDATA #REQUIRED
        aspectRatio   CDATA #REQUIRED>

<!ELEMENT UsedWindow EMPTY>
    <!ATTLIST UsedWindow
        name       CDATA #REQUIRED
        projection CDATA "EP"
        group      CDATA "Data">

<!ELEMENT Layout (Window+, Page+)>
    <!ATTLIST Layout
        name          CDATA #REQUIRED
        startup       CDATA #REQUIRED
        startupWindow CDATA #REQUIRED>

<!ELEMENT Window EMPTY>
    <!ATTLIST Window
        name   CDATA #REQUIRED
        hPos   CDATA #REQUIRED
        vPos   CDATA #REQUIRED
        width  CDATA #REQUIRED
        height CDATA #REQUIRED>

<!ELEMENT Page EMPTY>
    <!ATTLIST Page
        name    CDATA #REQUIRED
        content CDATA #REQUIRED>

<!ELEMENT Parameters (SuperGroup*)>
    <!ATTLIST Parameters
        userLevel CDATA #REQUIRED>

<!ELEMENT SuperGroup (Group*)>
    <!ATTLIST SuperGroup
        name    CDATA #REQUIRED
        toolTip CDATA ""
        userLevel CDATA "0">

<!ELEMENT Group (Command*,((ENUM)*, (SENUM)*, (ICUT)*, (SICUT)*, (FCUT)*, (SFCUT)*, (INT)*, (SINT)*,(LINT)*, (SLINT)*, (FLOAT)*, (SFLOAT)*, (COLOR)*, (SCOLOR)*, (StatusRoot)*, (STATUS)*, (LINK)*)* )>
    <!ATTLIST Group
        name      CDATA #REQUIRED
        sname     CDATA ""
        guiUsage  (NO_USE|TABLE|PROJECTION|BRAIN_TEST) "NO_USE"
        scope     (LOCAL|GLOBAL) "GLOBAL"
        userLevel CDATA "0"
        toolTip   CDATA "">

<!ELEMENT Command EMPTY>
    <!ATTLIST Command
        name    CDATA #REQUIRED
        command CDATA #REQUIRED
        ul      CDATA "0"
        toolTip CDATA "">

<!ENTITY none "0">

<!ELEMENT ENUM   EMPTY>	<!ATTLIST ENUM   fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf"                                                                           tip CDATA "" ul CDATA "0" scope CDATA "">
<!ELEMENT SENUM  EMPTY> <!ATTLIST SENUM  fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf" st (ON|OFF) #REQUIRED                                                     tip CDATA "" ul CDATA "0" scope CDATA "">
<!ELEMENT ICUT   EMPTY> <!ATTLIST ICUT   fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf"                       isMod (YES|NO) "NO" op CDATA #REQUIRED dop CDATA "" tip CDATA "" ul CDATA "0" scope CDATA "" u CDATA "&none;">
<!ELEMENT SICUT  EMPTY> <!ATTLIST SICUT  fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf" st (ON|OFF) #REQUIRED isMod (YES|NO) "NO" op CDATA #REQUIRED dop CDATA "" tip CDATA "" ul CDATA "0" scope CDATA "" u CDATA "&none;">
<!ELEMENT FCUT   EMPTY> <!ATTLIST FCUT   fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf"                       isMod (YES|NO) "NO" op CDATA #REQUIRED dop CDATA "" tip CDATA "" ul CDATA "0" scope CDATA "" u CDATA "&none;">
<!ELEMENT SFCUT  EMPTY> <!ATTLIST SFCUT  fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf" st (ON|OFF) #REQUIRED isMod (YES|NO) "NO" op CDATA #REQUIRED dop CDATA "" tip CDATA "" ul CDATA "0" scope CDATA "" u CDATA "&none;">
<!ELEMENT INT    EMPTY> <!ATTLIST INT    fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf"                       isMod (YES|NO) "NO"                                 tip CDATA "" ul CDATA "0" scope CDATA "" u CDATA "&none;">
<!ELEMENT SINT   EMPTY> <!ATTLIST SINT   fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf" st (ON|OFF) #REQUIRED isMod (YES|NO) "NO"                                 tip CDATA "" ul CDATA "0" scope CDATA "" u CDATA "&none;">
<!ELEMENT FLOAT  EMPTY> <!ATTLIST FLOAT  fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf"                       isMod (YES|NO) "NO"                                 tip CDATA "" ul CDATA "0" scope CDATA "" u CDATA "&none;">
<!ELEMENT SFLOAT EMPTY> <!ATTLIST SFLOAT fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf" st (ON|OFF) #REQUIRED isMod (YES|NO) "NO"                                 tip CDATA "" ul CDATA "0" scope CDATA "" u CDATA "&none;">
<!ELEMENT LINT   EMPTY> <!ATTLIST LINT   fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf"                                                                           tip CDATA "" ul CDATA "0" scope CDATA "" u CDATA "&none;">
<!ELEMENT SLINT  EMPTY> <!ATTLIST SLINT  fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf" st (ON|OFF) #REQUIRED                                                     tip CDATA "" ul CDATA "0" scope CDATA "" u CDATA "&none;">
<!ELEMENT COLOR  EMPTY> <!ATTLIST COLOR  fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf"                                                                           tip CDATA "" ul CDATA "0" scope CDATA "">
<!ELEMENT SCOLOR EMPTY> <!ATTLIST SCOLOR fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf" st (ON|OFF) #REQUIRED                                                     tip CDATA "" ul CDATA "0" scope CDATA "">
<!ELEMENT StatusRoot (StatusGroup*, STATUS*)>  <!ATTLIST StatusRoot  fn CDATA #REQUIRED sn CDATA "" st (ON|OFF) "OFF"     tip CDATA "" ul CDATA "0" scope CDATA "">
<!ELEMENT StatusGroup (StatusGroup*, STATUS*)> <!ATTLIST StatusGroup fn CDATA #REQUIRED sn CDATA "" st (ON|OFF) "OFF"     tip CDATA "" ul CDATA "0" scope CDATA "">
<!ELEMENT STATUS EMPTY>                        <!ATTLIST STATUS      fn CDATA #REQUIRED sn CDATA "" st (ON|OFF) #REQUIRED tip CDATA "" ul CDATA "0" scope CDATA "">
<!ELEMENT LINK   EMPTY> <!ATTLIST LINK to CDATA #REQUIRED>

<!ELEMENT ParameterDifferences (DIFFERENCE*)>

<!ELEMENT DIFFERENCE EMPTY>
    <!ATTLIST DIFFERENCE
        group      CDATA #REQUIRED
        name       CDATA #REQUIRED
        windowName CDATA #REQUIRED
        va         CDATA ""
        st         CDATA "" 
        op         CDATA "">

<!ELEMENT WindowCorners (CORNERS*)>

<!ELEMENT CORNERS EMPTY>
    <!ATTLIST CORNERS
        windowName CDATA #REQUIRED
        x0         CDATA #REQUIRED
        y0         CDATA #REQUIRED
        x1         CDATA #REQUIRED
        y1         CDATA #REQUIRED
        x2         CDATA #REQUIRED
        y2         CDATA #REQUIRED>

<!ENTITY length "1">
<!ENTITY energy "2">
<!ENTITY energyMEV "3">

<!ENTITY user "0">
<!ENTITY superuser "1">
<!ENTITY debug "3">

<!ENTITY assocCutOptions "All=0, Connected=1, Unconnected=2">
<!ENTITY drawTo          "Pixels = 0, Silicon Strips = 1, TRT_DriftCircle=2, LAr = 3, TILE = 4, Muon System = 5">
<!ENTITY colorFn         "Constant = 0, Simulated Track = 1, Reconstructed Track = 2, SubDetector = 3, Track Segment = 4">
<!ENTITY colorFnTRT      "Constant = 0, Simulated Track = 1, Reconstructed Track = 2, SubDetector = 3, Track Segment = 4, isOutlier = 5, driftSign = 6, threshold = 7">
<!ENTITY colorFnMTr      "Constant = 0, Index = 1, Pt = 2">
<!ENTITY colorFnCal      "Constant = 0, SubDetector = 1, Cluster = 2, Layer = 3, Energy = 4, Jet = 5, ECAL/HCAL = 6, Time = 7">
<!ENTITY colorFnS3D      "Constant = 0, Simulated Track = 1, Reconstructed Track = 2, SubDetector = 3, Group = 4, Layer = 5">
<!ENTITY colorFnTrigS3D  "Constant = 0, Simulated Track = 1, Reconstructed Track = 2, SubDetector = 3, Layer = 4">
<!ENTITY colorFnSiCluster "Constant = 0, Simulated Track = 1, Reconstructed Track = 2, SubDetector = 3, Layer = 4, Orientation=5">
<!ENTITY colorFnPixCluster "Constant = 0, Simulated Track = 1, Reconstructed Track = 2, SubDetector = 3, Layer = 4, Orientation=5, dE/dx=6">
<!ENTITY colorFnSTr      "Constant = 0, Index = 1, Pt = 2, Particle Type = 3, Origin Vertex = 4">
<!ENTITY colorFnRTr      "Constant = 0, Index = 1, Pt = 2, Collection = 3, Simulated Track = 4, RecVertex = 5, Objects = 7">
<!ENTITY colorFnBasic    "Constant = 0, Index = 1">
<!ENTITY colorFnBasicCollection "Constant = 0, Index = 1, Collection = 2">
<!ENTITY colorFnBasicCollectionBJets "Constant = 0, Index = 1, Collection = 2, BJets = 3">

<!ENTITY energyMode      "Sum (Linear) = 0, Max (Linear) = 1, Sum (Logarithmic) = 2, Max (Logarithmic) = 3, Sum (Square Root) = 4, Max (Square Root) = 5">
<!ENTITY symbol          "Filled Square=0, Horizontal Line=1,Vertical Line=2,Plus=3">
<!ENTITY pickingModes    "Event Data=0, Detectors=1">
<!ENTITY frameCol        "0,8:14">
<!ENTITY detectCol       "0:8,14">
<!ENTITY dataCol         "0,8,14:28">
<!ENTITY histoCol        "0,8,14:28">
<!ENTITY real            "&lt;,&gt;">
<!ENTITY eta             "&#x03B7;">
<!ENTITY rho             "&#x03C1;">
<!ENTITY phi             "&#x03A6;">
<!ENTITY delta           "&#x0394;">
<!ENTITY lambda          "&#x03BB;">
<!ENTITY sigma           "&#x03C3;">
<!ENTITY prime           "'">
<!ENTITY ne              "!=">
<!ENTITY le              "&lt;=">
<!ENTITY ge              "&gt;=">
<!ENTITY int             "=,&ne;,&lt;,&le;,&gt;,&ge;">
<!ENTITY intEqual        "=">
<!ENTITY modesFZ         "Standard = 0, RPC Middle 1 = 1, RPC Middle 2 = 2, RPC Outer = 3, MDT Inner and Extension = 4, MDT Middle = 5, MDT Outer = 6">
<!ENTITY modesYX         "Standard = 0, TGC Inner 1 = 1,TGC Middle 1 = 2, TGC Middle 2 = 3, TGC Middle 3 = 4, MDT/CSC Inner 1 = 5, MDT Extension = 6, MDT Middle = 7, MDT Outer = 8, FCAL EM= 9, FCAL HAD 1= 10, FCAL HAD 2= 11, LAr Ecap Presamp= 12, LAr Ecap 1= 13, LAr Ecap 2= 14, LAr Ecap 3= 15, HEC 1= 16, HEC 2= 17, HEC 3= 18, HEC 4= 19, LAr Ecap Summed=20, HEC Summed=21, MBTS=22">

]>


<AtlantisConfiguration>
	<Initialization>
		<Interactions>
			<InteractionControl projectionName="YX" defaultInDemoMode="YES" availableInDemoMode="YES">
				<Panel screenName="ZMR" fileName="ZMR" toolTip="Zoom/Move/Rotate"/>
				<Panel screenName="RubberBand" fileName="RubberbandYX" toolTip="Rubberband Selection"/>
				<Panel screenName="Pick" fileName="Pick" toolTip="Show Info for Picked Item"/>
				<Panel screenName="SyncCursors" fileName="SynchroCursors" toolTip="Synchronised Cursors"/>
				<Panel screenName="FishEye" fileName="FishEye" toolTip="FishEye Transformation"/>
				<Panel screenName="Clock" fileName="Clock" toolTip="Clock Transformation"/>
				<Panel screenName="Scale" fileName="ScaleCopy" toolTip="Scale Interaction"/>
			</InteractionControl>
			<InteractionControl projectionName="RZ" defaultInDemoMode="YES" availableInDemoMode="YES">
				<Panel screenName="ZMR" fileName="ZMR" toolTip="Zoom/Move/Rotate"/>
				<Panel screenName="RubberBand" fileName="Rubberband" toolTip="Rubberband Selection"/>
				<Panel screenName="Pick" fileName="Pick" toolTip="Show Info for Picked Item"/>
				<Panel screenName="SyncCursors" fileName="SynchroCursors" toolTip="Synchronised Cursors"/>
				<Panel screenName="FishEye" fileName="FishEye" toolTip="FishEye Transformation"/>
				<Panel screenName="Skew" fileName="Skew" toolTip="Skew Interaction"/>
				<Panel screenName="Scale" fileName="ScaleCopy" toolTip="Scale Interaction"/>
			</InteractionControl>
			<InteractionControl projectionName="XZ" defaultInDemoMode="NO" availableInDemoMode="YES">
				<Panel screenName="ZMR" fileName="ZMR" toolTip="Zoom/Move/Rotate"/>
				<Panel screenName="RubberBand" fileName="Rubberband" toolTip="Rubberband Selection"/>
				<Panel screenName="Pick" fileName="Pick" toolTip="Show Info for Picked Item"/>
				<Panel screenName="SyncCursors" fileName="SynchroCursors" toolTip="Synchronised Cursors"/>
				<Panel screenName="FishEye" fileName="FishEye" toolTip="FishEye Transformation"/>
				<Panel screenName="Scale" fileName="ScaleCopy" toolTip="Scale Interaction"/>
			</InteractionControl>
			<InteractionControl projectionName="YZ" defaultInDemoMode="NO" availableInDemoMode="YES">
				<Panel screenName="ZMR" fileName="ZMR" toolTip="Zoom/Move/Rotate"/>
				<Panel screenName="RubberBand" fileName="Rubberband" toolTip="Rubberband Selection"/>
				<Panel screenName="Pick" fileName="Pick" toolTip="Show Info for Picked Item"/>
				<Panel screenName="SyncCursors" fileName="SynchroCursors" toolTip="Synchronised Cursors"/>
				<Panel screenName="FishEye" fileName="FishEye" toolTip="FishEye Transformation"/>
				<Panel screenName="Scale" fileName="ScaleCopy" toolTip="Scale Interaction"/>
			</InteractionControl>
			<InteractionControl projectionName="FZ" defaultInDemoMode="NO" availableInDemoMode="YES">
				<Panel screenName="ZMR" fileName="ZMR" toolTip="Zoom/Move/Rotate"/>
				<Panel screenName="RubberBand" fileName="Rubberband" toolTip="Rubberband Selection"/>
				<Panel screenName="Pick" fileName="Pick" toolTip="Show Info for Picked Item"/>
				<Panel screenName="SyncCursors" fileName="SynchroCursors" toolTip="Synchronised Cursors"/>
				<Panel screenName="FishEye" fileName="FishEye" toolTip="FishEye Transformation"/>
				<Panel screenName="Skew" fileName="Skew" toolTip="Skew Interaction"/>
				<Panel screenName="Scale" fileName="ScaleCopy" toolTip="Scale Interaction"/>
			</InteractionControl>
			<InteractionControl projectionName="FR" defaultInDemoMode="NO" availableInDemoMode="YES">
				<Panel screenName="ZMR" fileName="ZMR" toolTip="Zoom/Move/Rotate"/>
				<Panel screenName="RubberBand" fileName="RubberbandYX" toolTip="Rubberband Selection"/>
				<Panel screenName="Pick" fileName="Pick" toolTip="Show Info for Picked Item"/>
				<Panel screenName="SyncCursors" fileName="SynchroCursors" toolTip="Synchronised Cursors"/>
				<Panel screenName="FishEye" fileName="FishEye" toolTip="FishEye Transformation"/>
				<Panel screenName="Skew" fileName="Skew" toolTip="Skew Interaction"/>
				<Panel screenName="Scale" fileName="ScaleCopy" toolTip="Scale Interaction"/>
			</InteractionControl>
			<InteractionControl projectionName="VP" defaultInDemoMode="YES" availableInDemoMode="YES">
				<Panel screenName="RubberBand" fileName="VPSelection" toolTip="Rubberband Selection"/>
				<Panel screenName="Pick" fileName="Pick" toolTip="Show Info for Picked Item"/>
				<Panel screenName="ZMR" fileName="ZMR" toolTip="Zoom/Move/Rotate"/>
				<Panel screenName="SyncCursors" fileName="SynchroCursors" toolTip="Synchronised Cursors"/>
				<Panel screenName="Scale" fileName="ScaleCopy" toolTip="Scale Interaction"/>
			</InteractionControl>
			<InteractionControl projectionName="3D" defaultInDemoMode="NO" availableInDemoMode="NO">
				<Panel screenName="ZMR" fileName="ZMR" toolTip="Zoom/Move/Rotate"/>
				<Panel screenName="RubberBand" fileName="VPSelection" toolTip="Rubberband Selection"/>
				<Panel screenName="Pick" fileName="Pick" toolTip="Show Info for Picked Item"/>
				<Panel screenName="FishEye" fileName="FishEye" toolTip="FishEye Transformation"/>
				<Panel screenName="SyncCursors" fileName="SynchroCursors" toolTip="Synchronised Cursors"/>
				<Panel screenName="Scale" fileName="ScaleCopy" toolTip="Scale Interaction"/>
			</InteractionControl>
			<InteractionControl projectionName="3DBox" defaultInDemoMode="NO" availableInDemoMode="NO">
				<Panel screenName="ZR" fileName="3DBox" toolTip="Zoom/Rotate"/>
			</InteractionControl>
			<InteractionControl projectionName="LegoPlot" defaultInDemoMode="NO" availableInDemoMode="YES">
				<Panel screenName="ZMR" fileName="ZMR" toolTip="Zoom/Move/Rotate"/>
				<Panel screenName="SyncCursors" fileName="SynchroCursors" toolTip="Synchronised Cursors"/>
			</InteractionControl>
			<InteractionControl projectionName="TrackResidual" defaultInDemoMode="NO" availableInDemoMode="NO">
				<Panel screenName="Pick" fileName="Pick" toolTip="Show Info for Picked Item"/>
			</InteractionControl>
			<InteractionControl projectionName="N3D" defaultInDemoMode="NO" availableInDemoMode="YES">
				<Panel screenName="Rotate" fileName="NZMR" toolTip="Zoom/Move/Rotate"/>
			</InteractionControl>
			<InteractionControl projectionName="NYX" defaultInDemoMode="NO" availableInDemoMode="YES">
			</InteractionControl>
			<InteractionControl projectionName="NPhysics" defaultInDemoMode="NO" availableInDemoMode="YES">
				<Panel screenName="Rotate" fileName="NZMR" toolTip="Zoom/Move/Rotate"/>
			</InteractionControl>
			<InteractionControl projectionName="EventInfo" defaultInDemoMode="NO" availableInDemoMode="YES">
			</InteractionControl>
		</Interactions>
		<Canvas aspectRatio="0.9252217997465145" startupLayout="FULL SCREEN">
			<UsedWindow group="Data" projection="YX" name="1"/>
			<UsedWindow group="Data" projection="FR" name="2"/>
			<UsedWindow group="Data" projection="FZ" name="3"/>
			<UsedWindow group="Data" projection="YZ" name="4"/>
			<UsedWindow group="Data" projection="RZ" name="5"/>
			<UsedWindow group="Data" projection="VP" name="6"/>
			<UsedWindow group="Data" projection="XZ" name="7"/>
			<UsedWindow group="Data" projection="VP" name="8"/>
			<UsedWindow group="Data" projection="LegoPlot" name="9"/>
			<UsedWindow group="YX" projection="YX" name="L"/>
			<UsedWindow group="InDetTrack" projection="YX" name="M"/>
			<UsedWindow group="CutsInDet" projection="RZ" name="R"/>
			<UsedWindow group="Data" projection="YX" name="U"/>
			<UsedWindow group="Data" projection="FR" name="C"/>
			<UsedWindow group="LegoPlot" projection="LegoPlot" name="D"/>
			<UsedWindow group="Data" projection="FZ" name="E"/>
			<UsedWindow group="Data" projection="YX" name="S"/>
			<UsedWindow group="Data" projection="YX" name="W"/>
			<UsedWindow group="InDetTrack" projection="RZ" name="B"/>
			<Layout startupWindow="S" startup="S36" name="LANDSCAPE">
				<Window hPos="0" height="1" vPos="0" width="1" name="1"/>
				<Window hPos="1" height="1" vPos="0" width="1" name="2"/>
				<Window hPos="2" height="1" vPos="0" width="1" name="3"/>
				<Window hPos="0" height="1" vPos="1" width="1" name="4"/>
				<Window hPos="1" height="1" vPos="1" width="1" name="5"/>
				<Window hPos="2" height="1" vPos="1" width="1" name="6"/>
				<Window hPos="0" height="2" vPos="0" width="1" name="L"/>
				<Window hPos="1" height="2" vPos="0" width="1" name="M"/>
				<Window hPos="2" height="2" vPos="0" width="1" name="R"/>
				<Window hPos="0" height="1" vPos="0" width="2" name="U"/>
				<Window hPos="0" height="1" vPos="1" width="2" name="B"/>
				<Window hPos="0" height="2" vPos="0" width="2" name="S"/>
				<Window hPos="0" height="2" vPos="0" width="3" name="W"/>
				<Page content="123456" name="Full"/>
				<Page content="LMR" name="Vert"/>
				<Page content="SR" name="Rect"/>
				<Page content="UBR" name="Hori"/>
				<Page content="W" name="W"/>
			</Layout>
			<Layout startupWindow="S" startup="SB" name="PORTRAIT">
				<Window hPos="0" height="1" vPos="0" width="1" name="1"/>
				<Window hPos="1" height="1" vPos="0" width="1" name="2"/>
				<Window hPos="0" height="1" vPos="1" width="1" name="3"/>
				<Window hPos="1" height="1" vPos="1" width="1" name="4"/>
				<Window hPos="0" height="1" vPos="2" width="1" name="5"/>
				<Window hPos="1" height="1" vPos="2" width="1" name="6"/>
				<Window hPos="0" height="1" vPos="0" width="2" name="U"/>
				<Window hPos="0" height="1" vPos="1" width="2" name="C"/>
				<Window hPos="0" height="1" vPos="2" width="2" name="B"/>
				<Window hPos="0" height="2" vPos="0" width="2" name="S"/>
				<Window hPos="0" height="3" vPos="0" width="2" name="W"/>
				<Page content="123456" name="Full"/>
				<Page content="SB" name="Rect"/>
				<Page content="UCB" name="Hori"/>
				<Page content="W" name="W"/>
			</Layout>
			<Layout startupWindow="S" startup="S369" name="SQUARE B">
				<Window hPos="0" height="1" vPos="0" width="1" name="1"/>
				<Window hPos="1" height="1" vPos="0" width="1" name="2"/>
				<Window hPos="2" height="1" vPos="0" width="1" name="3"/>
				<Window hPos="0" height="1" vPos="1" width="1" name="4"/>
				<Window hPos="1" height="1" vPos="1" width="1" name="5"/>
				<Window hPos="2" height="1" vPos="1" width="1" name="6"/>
				<Window hPos="0" height="1" vPos="2" width="1" name="7"/>
				<Window hPos="1" height="1" vPos="2" width="1" name="8"/>
				<Window hPos="2" height="1" vPos="2" width="1" name="9"/>
				<Window hPos="0" height="3" vPos="0" width="3" name="W"/>
				<Window hPos="0" height="3" vPos="0" width="2" name="S"/>
				<Window hPos="0" height="3" vPos="0" width="1" name="L"/>
				<Window hPos="1" height="3" vPos="0" width="1" name="M"/>
				<Window hPos="2" height="3" vPos="0" width="1" name="R"/>
				<Window hPos="0" height="1" vPos="0" width="3" name="U"/>
				<Window hPos="0" height="1" vPos="1" width="3" name="C"/>
				<Window hPos="0" height="1" vPos="2" width="3" name="B"/>
				<Page content="123456789" name="Full"/>
				<Page content="SR" name="Rect"/>
				<Page content="LMR" name="Hori"/>
				<Page content="UCB" name="Vert"/>
				<Page content="W" name="W"/>
			</Layout>
			<Layout startupWindow="S" startup="SRB" name="SQUARE">
				<Window hPos="0" height="1" vPos="0" width="1" name="1"/>
				<Window hPos="1" height="1" vPos="0" width="1" name="2"/>
				<Window hPos="2" height="1" vPos="0" width="1" name="3"/>
				<Window hPos="0" height="1" vPos="1" width="1" name="4"/>
				<Window hPos="1" height="1" vPos="1" width="1" name="5"/>
				<Window hPos="2" height="1" vPos="1" width="1" name="6"/>
				<Window hPos="0" height="1" vPos="2" width="1" name="7"/>
				<Window hPos="1" height="1" vPos="2" width="1" name="8"/>
				<Window hPos="2" height="1" vPos="2" width="1" name="9"/>
				<Window hPos="0" height="2" vPos="0" width="2" name="S"/>
				<Window hPos="0" height="2" vPos="0" width="1" name="L"/>
				<Window hPos="1" height="2" vPos="0" width="1" name="M"/>
				<Window hPos="2" height="2" vPos="0" width="1" name="R"/>
				<Window hPos="0" height="1" vPos="0" width="2" name="U"/>
				<Window hPos="0" height="1" vPos="1" width="2" name="C"/>
				<Window hPos="0" height="1" vPos="2" width="2" name="D"/>
				<Window hPos="0" height="1" vPos="2" width="3" name="B"/>
				<Window hPos="0" height="3" vPos="0" width="3" name="W"/>
				<Page content="123456789" name="Full"/>
				<Page content="LMRB" name="Hori"/>
				<Page content="UCD369" name="Vert"/>
				<Page content="SRB" name="All"/>
				<Page content="W" name="W"/>
			</Layout>
			<Layout startupWindow="1" startup="1234" name="FOUR SQUARES">
				<Window hPos="0" height="1" vPos="0" width="1" name="1"/>
				<Window hPos="1" height="1" vPos="0" width="1" name="2"/>
				<Window hPos="0" height="1" vPos="1" width="1" name="3"/>
				<Window hPos="1" height="1" vPos="1" width="1" name="4"/>
				<Window hPos="0" height="1" vPos="1" width="2" name="B"/>
				<Window hPos="0" height="2" vPos="0" width="2" name="W"/>
				<Page content="1234" name="Four"/>
				<Page content="12B" name="Three"/>
				<Page content="W" name="W"/>
			</Layout>
			<Layout startupWindow="R" startup="DLMBR" name="FULL SCREEN">
				<Window hPos="0" height="2" vPos="0" width="2" name="S"/>
				<Window hPos="2" height="1" vPos="0" width="1" name="R"/>
				<Window hPos="2" height="1" vPos="1" width="1" name="D"/>
				<Window hPos="2" height="2" vPos="0" width="1" name="E"/>
				<Window hPos="0" height="1" vPos="0" width="1" name="L"/>
				<Window hPos="1" height="1" vPos="0" width="1" name="M"/>
				<Window hPos="0" height="1" vPos="1" width="2" name="B"/>
				<Window hPos="0" height="2" vPos="0" width="3" name="W"/>
				<Page content="SE" name="Two"/>
				<Page content="SRD" name="Three"/>
				<Page content="LMRBD" name="Five"/>
				<Page content="W" name="W"/>
			</Layout>
		</Canvas>
	</Initialization>
	<Parameters userLevel="0">
		<SuperGroup userLevel="0" toolTip="Projection Selection" name="Projection">
			<Group userLevel="0" guiUsage="NO_USE" scope="LOCAL" sname="" toolTip="Projection Parameters" name="Projection">
				<FLOAT u="1" sn="" ul="0" scope="" isMod="NO" pv="0:inf" va="1320.0" fn="Radius" tip="default detector radius"/>
				<FLOAT u="1" sn="" ul="0" scope="" isMod="NO" pv="0:inf" va="2250.0" fn="Length" tip="default detector length"/>
				<FLOAT u="1" sn="" ul="0" scope="" isMod="NO" pv="0:inf" va="1320.0" fn="TrackingRadius" tip="default detector radius"/>
				<FLOAT u="1" sn="" ul="0" scope="" isMod="NO" pv="0:inf" va="2250.0" fn="TrackingLength" tip="default detector length"/>
				<FLOAT u="2" sn="" ul="3" scope="" isMod="NO" pv="1:inf" va="1000.0" fn="Energy Max" tip=""/>
				<STATUS sn="" ul="0" st="OFF" scope="" fn="Skip Data" tip="Skip drawing of data during interaction if F key down"/>
			</Group>
			<Group userLevel="0" guiUsage="PROJECTION" scope="LOCAL" sname="" toolTip="YX Projection" name="YX">
				<ENUM sn="View" scope="" ul="0" pv="Standard = 0, TGC Inner 1 = 1,TGC Middle 1 = 2, TGC Middle 2 = 3, TGC Middle 3 = 4, MDT/CSC Inner 1 = 5, MDT Extension = 6, MDT Middle = 7, MDT Outer = 8, FCAL EM= 9, FCAL HAD 1= 10, FCAL HAD 2= 11, LAr Ecap Presamp= 12, LAr Ecap 1= 13, LAr Ecap 2= 14, LAr Ecap 3= 15, HEC 1= 16, HEC 2= 17, HEC 3= 18, HEC 4= 19, LAr Ecap Summed=20, HEC Summed=21, MBTS=22" va="0" fn="Mode" tip="View Mode"/>
				<ENUM sn="Summed LAr binning" scope="GLOBAL" ul="0" pv="0.1x0.1=1,0.2x0.2=2,split=3" va="1" fn="LArBin" tip="Shows the binning for the LAr Summed endcap view for &eta; and &phi;"/>
				<ENUM sn="Summed HEC binning" scope="GLOBAL" ul="0" pv="0.1x0.1=1,0.2x0.2=2,split=3" va="2" fn="HECBin" tip="Shows the binning for the HEC Summed endcap view for &eta; and &phi;"/>
				<FLOAT u="0" sn="Eta of split binning" ul="0" scope="" isMod="NO" pv="0:inf" va="2.5" fn="SplitEta" tip="On summed binning seperates the split binning 0.1x0.1 below eta and 0.2x0.2 above eta, minimum 1.2 and only keeps 1 decimal place"/>
				<STATUS sn="Draw FCAL inside HEC" ul="0" st="OFF" scope="GLOBAL" fn="DrawFCAL" tip="Draws the FCAL layers inside the relevant individual layers of the HEC (2,3,4)"/>
				<SLINT u="0" sn="" ul="0" scope="" pv="1:4" st="OFF" va="1" fn="CSC Gas Gap" tip="Gas Gap in Cathode Strip Chambers"/>
				<SLINT u="0" sn="" ul="0" scope="" pv="1:3" st="OFF" va="1" fn="TGC Gas Gap" tip="Gas Gap in Thin Gap Chambers"/>
				<FLOAT u="0" sn="&phi; for Clock interaction" ul="1" scope="" isMod="NO" pv="0:360" va="0.0" fn="Phi" tip="&phi; angle for clock zoom interaction (Clock interaction must be activated)"/>
				<SFLOAT u="0" sn="" ul="3" scope="" isMod="NO" pv="0:inf" st="OFF" va="1.5" fn="FishEye" tip="Fish Eye zoom factor value"/>
				<SFLOAT u="0" sn="" ul="3" scope="" isMod="NO" pv="0:inf" st="OFF" va="3.0" fn="Clock" tip="Clock zoom factor value"/>
				<FLOAT u="1" sn="&rho; To" ul="3" scope="" isMod="NO" pv="0:inf" va="1100.0" fn="rTo" tip="&rho; value for Fish Eye zoom (interaction)"/>
				<STATUS sn="&rho;Z Cutting Plane" ul="0" st="OFF" scope="" fn="RZ Cutting Plane" tip="Show cutting plane of projection &rho;Z"/>
			</Group>
			<Group userLevel="0" guiUsage="PROJECTION" scope="LOCAL" sname="&phi;&eta;" toolTip="&phi;&eta; Projection" name="VP">
				<Command command="SETORIGINALPRIMARYVERTEX" ul="0" name="Set Original Primary Vertex" toolTip="Set original primary vertex of the current event"/>
				<ENUM sn="View" scope="" ul="0" pv="Standard=0,SpacePoint=1,TRT_DriftCircle=2,ECAL Sampling 0=3,ECAL Sampling 1=4,ECAL Sampling 2=5,ECAL Sampling 3=6,HCAL Sampling 0=7,HCAL Sampling 1=8,HCAL Sampling 2=9,HCAL Sampling 3=10" va="0" fn="Mode" tip="View Mode"/>
				<STATUS sn="&eta; Vertex" ul="0" st="ON" scope="" fn="Eta Vertex" tip="Recalculates &eta; from &rho; and z for calorimeter cells from primary vertex instead of from 0 (shall always be on)"/>
				<LINK to="Event.XVtx"/>
				<LINK to="Event.YVtx"/>
				<LINK to="Event.ZVtx"/>
				<SFLOAT u="1" sn="&rho; Max" ul="0" scope="" isMod="NO" pv="0:inf" st="OFF" va="122.0" fn="R Max" tip="Maximal &rho; of Tip of V"/>
				<SFLOAT u="1" sn="" ul="0" scope="" isMod="NO" pv="0:inf" st="OFF" va="265.0" fn="Z Max" tip="Maximal Z of Tip of V"/>
				<FLOAT u="0" sn="" ul="0" scope="" isMod="NO" pv="0:inf" va="5.0" fn="Gradient" tip="Gradient of V Arms"/>
				<SFLOAT u="0" sn="" ul="0" scope="" isMod="NO" pv="-inf : inf" st="OFF" va="0.4" fn="Short V" tip="Draw Short V (only if SpacePoint are turned off)"/>
				<SCOLOR sn="VPlot calo island" scope="" ul="0" pv="0:8,14" st="ON" va="8" fn="VPlot Island" tip="Select the color for islands for calorimeter detail zoom (island is a common structure for all calo layers)"/>
				<STATUS sn="" ul="0" st="OFF" scope="" fn="DrawApex" tip="Draw Symbol at Apex of V"/>
				<ENUM sn="Jet" scope="" ul="0" pv="ET=0, E=1" va="0" fn="Jet" tip="Select the Energy Type for Drawing Jets"/>
				<INT u="0" sn="" ul="3" scope="" isMod="NO" pv="-inf:inf" va="-1" fn="Initial Frame" tip=""/>
				<INT u="0" sn="" ul="3" scope="" isMod="NO" pv="0:inf" va="3" fn="Frames Count" tip=""/>
				<INT u="0" sn="&phi; Wrap" ul="3" scope="" isMod="NO" pv="0:inf" va="0" fn="Phi Wrap" tip=""/>
			</Group>
			<Group userLevel="0" guiUsage="PROJECTION" scope="LOCAL" sname="&rho;Z" toolTip="&rho;Z Projection" name="RZ">
				<ENUM sn="View" scope="" ul="3" pv="Standard=0" va="0" fn="Mode" tip=""/>
				<FLOAT u="0" sn="&phi;" ul="0" scope="" isMod="NO" pv="0:360" va="90.0" fn="Phi" tip="Cutting Plane Angle"/>
				<STATUS sn="TRT_DriftCircle" ul="0" st="OFF" scope="" fn="TRT" tip="Draw TRT_DriftCircle"/>
				<SFLOAT u="0" sn="" ul="3" scope="" isMod="NO" pv="0:inf" st="OFF" va="0.0" fn="FishEye" tip=""/>
				<FLOAT u="1" sn="&rho; To" ul="3" scope="" isMod="NO" pv="0:inf" va="1100.0" fn="rTo" tip=""/>
				<FLOAT u="1" sn="" ul="3" scope="" isMod="NO" pv="0:inf" va="2300.0" fn="zTo" tip=""/>
			</Group>
			<Group userLevel="0" guiUsage="PROJECTION" scope="LOCAL" sname="&phi;&rho;" toolTip="&phi;&rho; Projection" name="FR">
				<LINK to="YX.Mode"/>
				<LINK to="YX.LArBin"/>
				<LINK to="YX.HECBin"/>
				<LINK to="YX.DrawFCAL"/>