=== ScythiansCloud/ATLAS/atlas-group-7-main/atlas-group-7-main/Atlantis/configuration/config.dtd
<!ELEMENT AtlantisConfiguration (Initialization, Parameters,ParameterDifferences*, WindowCorners*)>

<!ELEMENT Initialization (Interactions, Canvas)>

<!ELEMENT Interactions (Panel*, InteractionControl+)>

<!ELEMENT InteractionControl (Panel*)>
    <!ATTLIST InteractionControl
        projectionName    CDATA #REQUIRED
        availableInDemoMode     CDATA "YES"
        defaultInDemoMode CDATA "NO" >

<!ELEMENT Panel EMPTY>
    <!ATTLIST Panel
        screenName CDATA #REQUIRED
        fileName   CDATA #REQUIRED
        toolTip    CDATA "">

<!ELEMENT Canvas (UsedWindow+, Layout+)>
    <!ATTLIST Canvas
        startupLayout CDATA #REQUIRED
        aspectRatio   CDATA #REQUIRED>

<!ELEMENT UsedWindow EMPTY>
    <!ATTLIST UsedWindow
        name       CDATA #REQUIRED
        projection CDATA "EP"
        group      CDATA "Data">

<!ELEMENT Layout (Window+, Page+)>
    <!ATTLIST Layout
        name          CDATA #REQUIRED
        startup       CDATA #REQUIRED
        startupWindow CDATA #REQUIRED>

<!ELEMENT Window EMPTY>
    <!ATTLIST Window
        name   CDATA #REQUIRED
        hPos   CDATA #REQUIRED
        vPos   CDATA #REQUIRED
        width  CDATA #REQUIRED
        height CDATA #REQUIRED>

<!ELEMENT Page EMPTY>
    <!ATTLIST Page
        name    CDATA #REQUIRED
        content CDATA #REQUIRED>

<!ELEMENT Parameters (SuperGroup*)>
    <!ATTLIST Parameters
        userLevel CDATA #REQUIRED>

<!ELEMENT SuperGroup (Group*)>
    <!ATTLIST SuperGroup
        name    CDATA #REQUIRED
        toolTip CDATA ""
        userLevel CDATA "0">

<!ELEMENT Group (Command*,((ENUM)*, (SENUM)*, (ICUT)*, (SICUT)*, (FCUT)*, (SFCUT)*, (INT)*, (SINT)*,(LINT)*, (SLINT)*, (FLOAT)*, (SFLOAT)*, (COLOR)*, (SCOLOR)*, (StatusRoot)*, (STATUS)*, (LINK)*)* )>
    <!ATTLIST Group
        name      CDATA #REQUIRED
        sname     CDATA ""
        guiUsage  (NO_USE|TABLE|PROJECTION|BRAIN_TEST) "NO_USE"
        scope     (LOCAL|GLOBAL) "GLOBAL"
        userLevel CDATA "0"
        toolTip   CDATA "">

<!ELEMENT Command EMPTY>
    <!ATTLIST Command
        name    CDATA #REQUIRED
        command CDATA #REQUIRED
        ul      CDATA "0"
        toolTip CDATA "">

<!ENTITY none "0">

<!ELEMENT ENUM   EMPTY>	<!ATTLIST ENUM   fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf"                                                                           tip CDATA "" ul CDATA "0" scope CDATA "">
<!ELEMENT SENUM  EMPTY> <!ATTLIST SENUM  fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf" st (ON|OFF) #REQUIRED                                                     tip CDATA "" ul CDATA "0" scope CDATA "">
<!ELEMENT ICUT   EMPTY> <!ATTLIST ICUT   fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf"                       isMod (YES|NO) "NO" op CDATA #REQUIRED dop CDATA "" tip CDATA "" ul CDATA "0" scope CDATA "" u CDATA "&none;">
<!ELEMENT SICUT  EMPTY> <!ATTLIST SICUT  fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf" st (ON|OFF) #REQUIRED isMod (YES|NO) "NO" op CDATA #REQUIRED dop CDATA "" tip CDATA "" ul CDATA "0" scope CDATA "" u CDATA "&none;">
<!ELEMENT FCUT   EMPTY> <!ATTLIST FCUT   fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf"                       isMod (YES|NO) "NO" op CDATA #REQUIRED dop CDATA "" tip CDATA "" ul CDATA "0" scope CDATA "" u CDATA "&none;">
<!ELEMENT SFCUT  EMPTY> <!ATTLIST SFCUT  fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf" st (ON|OFF) #REQUIRED isMod (YES|NO) "NO" op CDATA #REQUIRED dop CDATA "" tip CDATA "" ul CDATA "0" scope CDATA "" u CDATA "&none;">
<!ELEMENT INT    EMPTY> <!ATTLIST INT    fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf"                       isMod (YES|NO) "NO"                                 tip CDATA "" ul CDATA "0" scope CDATA "" u CDATA "&none;">
<!ELEMENT SINT   EMPTY> <!ATTLIST SINT   fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf" st (ON|OFF) #REQUIRED isMod (YES|NO) "NO"                                 tip CDATA "" ul CDATA "0" scope CDATA "" u CDATA "&none;">
<!ELEMENT FLOAT  EMPTY> <!ATTLIST FLOAT  fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf"                       isMod (YES|NO) "NO"                                 tip CDATA "" ul CDATA "0" scope CDATA "" u CDATA "&none;">
<!ELEMENT SFLOAT EMPTY> <!ATTLIST SFLOAT fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf" st (ON|OFF) #REQUIRED isMod (YES|NO) "NO"                                 tip CDATA "" ul CDATA "0" scope CDATA "" u CDATA "&none;">
<!ELEMENT LINT   EMPTY> <!ATTLIST LINT   fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf"                                                                           tip CDATA "" ul CDATA "0" scope CDATA "" u CDATA "&none;">
<!ELEMENT SLINT  EMPTY> <!ATTLIST SLINT  fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf" st (ON|OFF) #REQUIRED                                                     tip CDATA "" ul CDATA "0" scope CDATA "" u CDATA "&none;">
<!ELEMENT COLOR  EMPTY> <!ATTLIST COLOR  fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf"                                                                           tip CDATA "" ul CDATA "0" scope CDATA "">
<!ELEMENT SCOLOR EMPTY> <!ATTLIST SCOLOR fn CDATA #REQUIRED sn CDATA "" va CDATA #REQUIRED pv CDATA "-inf : inf" st (ON|OFF) #REQUIRED                                                     tip CDATA "" ul CDATA "0" scope CDATA "">
<!ELEMENT StatusRoot (StatusGroup*, STATUS*)>  <!ATTLIST StatusRoot  fn CDATA #REQUIRED sn CDATA "" st (ON|OFF) "OFF"     tip CDATA "" ul CDATA "0" scope CDATA "">
<!ELEMENT StatusGroup (StatusGroup*, STATUS*)> <!ATTLIST StatusGroup fn CDATA #REQUIRED sn CDATA "" st (ON|OFF) "OFF"     tip CDATA "" ul CDATA "0" scope CDATA "">
<!ELEMENT STATUS EMPTY>                        <!ATTLIST STATUS      fn CDATA #REQUIRED sn CDATA "" st (ON|OFF) #REQUIRED tip CDATA "" ul CDATA "0" scope CDATA "">
<!ELEMENT LINK   EMPTY> <!ATTLIST LINK to CDATA #REQUIRED>

<!ELEMENT ParameterDifferences (DIFFERENCE*)>

<!ELEMENT DIFFERENCE EMPTY>
    <!ATTLIST DIFFERENCE
        group      CDATA #REQUIRED
        name       CDATA #REQUIRED
        windowName CDATA "*"
        va         CDATA ""
        st         CDATA "" 
        op         CDATA "">

<!ELEMENT WindowCorners (CORNERS*)>

<!ELEMENT CORNERS EMPTY>
    <!ATTLIST CORNERS
        windowName CDATA #REQUIRED
        x0         CDATA #REQUIRED
        y0         CDATA #REQUIRED
        x1         CDATA #REQUIRED
        y1         CDATA #REQUIRED
        x2         CDATA #REQUIRED
        y2         CDATA #REQUIRED>

<!ENTITY length "1">
<!ENTITY energy "2">
<!ENTITY energyMEV "3">

<!ENTITY user "0">
<!ENTITY superuser "1">
<!ENTITY debug "3">

<!ENTITY assocCutOptions "All=0, Connected=1, Unconnected=2">
<!ENTITY drawTo          "Pixels = 0, Silicon Strips = 1, TRT_DriftCircle=2, LAr = 3, TILE = 4, Muon System = 5">
<!ENTITY colorFn         "Constant = 0, Simulated Track = 1, Reconstructed Track = 2, SubDetector = 3, Track Segment = 4">
<!ENTITY colorFnTRT      "Constant = 0, Simulated Track = 1, Reconstructed Track = 2, SubDetector = 3, Track Segment = 4, isOutlier = 5, driftSign = 6, threshold = 7">
<!ENTITY colorFnMTr      "Constant = 0, Index = 1, Pt = 2">
<!ENTITY colorFnCal      "Constant = 0, SubDetector = 1, Cluster = 2, Layer = 3, Energy = 4, Jet = 5, ECAL/HCAL = 6, Time = 7">
<!ENTITY colorFnS3D      "Constant = 0, Simulated Track = 1, Reconstructed Track = 2, SubDetector = 3, Group = 4, Layer = 5">
<!ENTITY colorFnTrigS3D  "Constant = 0, Simulated Track = 1, Reconstructed Track = 2, SubDetector = 3, Layer = 4">
<!ENTITY colorFnSiCluster "Constant = 0, Simulated Track = 1, Reconstructed Track = 2, SubDetector = 3, Layer = 4, Orientation=5">
<!ENTITY colorFnPixCluster "Constant = 0, Simulated Track = 1, Reconstructed Track = 2, SubDetector = 3, Layer = 4, Orientation=5, dE/dx=6">
<!ENTITY colorFnSTr      "Constant = 0, Index = 1, Pt = 2, Particle Type = 3, Origin Vertex = 4">
<!ENTITY colorFnRTr      "Constant = 0, Index = 1, Pt = 2, Collection = 3, Simulated Track = 4, RecVertex = 5, Objects = 7">
<!ENTITY colorFnBasic    "Constant = 0, Index = 1">
<!ENTITY colorFnBasicCollection "Constant = 0, Index = 1, Collection = 2">
<!ENTITY colorFnBasicCollectionBJets "Constant = 0, Index = 1, Collection = 2, BJets = 3">

<!ENTITY energyMode      "Sum (Linear) = 0, Max (Linear) = 1, Sum (Logarithmic) = 2, Max (Logarithmic) = 3, Sum (Square Root) = 4, Max (Square Root) = 5">
<!ENTITY symbol          "Filled Square=0, Horizontal Line=1,Vertical Line=2,Plus=3">
<!ENTITY pickingModes    "Event Data=0, Detectors=1">
<!ENTITY frameCol        "0,8:14">
<!ENTITY detectCol       "0:8,14">
<!ENTITY dataCol         "0,8,14:28">
<!ENTITY histoCol        "0,8,14:28">
<!ENTITY real            "&lt;,&gt;">
<!ENTITY eta             "&#x03B7;">
<!ENTITY rho             "&#x03C1;">
<!ENTITY phi             "&#x03A6;">
<!ENTITY delta           "&#x0394;">
<!ENTITY lambda          "&#x03BB;">
<!ENTITY sigma           "&#x03C3;">
<!ENTITY prime           "'">
<!ENTITY ne              "!=">
<!ENTITY le              "&lt;=">
<!ENTITY ge              "&gt;=">
<!ENTITY int             "=,&ne;,&lt;,&le;,&gt;,&ge;">
<!ENTITY intEqual        "=">
<!ENTITY modesFZ         "Standard = 0, RPC Middle 1 = 1, RPC Middle 2 = 2, RPC Outer = 3, MDT Inner and Extension = 4, MDT Middle = 5, MDT Outer = 6">
<!ENTITY modesYX         "Standard = 0, TGC Inner 1 = 1,TGC Middle 1 = 2, TGC Middle 2 = 3, TGC Middle 3 = 4, MDT/CSC Inner 1 = 5, MDT Extension = 6, MDT Middle = 7, MDT Outer = 8, FCAL EM= 9, FCAL HAD 1= 10, FCAL HAD 2= 11, LAr Ecap Presamp= 12, LAr Ecap 1= 13, LAr Ecap 2= 14, LAr Ecap 3= 15, HEC 1= 16, HEC 2= 17, HEC 3= 18, HEC 4= 19, LAr Ecap Summed=20, HEC Summed=21, MBTS=22">

<!-- Entities for including blocks of common data -->
<!ENTITY CommonInteractions SYSTEM "common-interactions.xml">
<!ENTITY CommonParameters   SYSTEM "common-parameters.xml">

=== ScythiansCloud/ATLAS/atlas-group-7-main/atlas-group-7-main/Atlantis/configuration/config.xml
<?xml version="1.0"?>
<!DOCTYPE AtlantisConfiguration SYSTEM "config.dtd">
<AtlantisConfiguration>
    <Initialization>
        <Interactions>
            <InteractionControl availableInDemoMode="YES" defaultInDemoMode="YES" projectionName="YX">
                <Panel fileName="ZMR" screenName="ZMR" toolTip="Zoom/Move/Rotate"/>
                <Panel fileName="RubberbandYX" screenName="RubberBand" toolTip="Rubberband Selection"/>
                <Panel fileName="Pick" screenName="Pick" toolTip="Show Info for Picked Item"/>
                <Panel fileName="SynchroCursors" screenName="SyncCursors" toolTip="Synchronised Cursors"/>
                <Panel fileName="FishEye" screenName="FishEye" toolTip="FishEye Transformation"/>
                <Panel fileName="Clock" screenName="Clock" toolTip="Clock Transformation"/>
                <Panel fileName="ScaleCopy" screenName="Scale" toolTip="Scale Interaction"/>
            </InteractionControl>
            <InteractionControl availableInDemoMode="YES" defaultInDemoMode="YES" projectionName="RZ">
                <Panel fileName="ZMR" screenName="ZMR" toolTip="Zoom/Move/Rotate"/>
                <Panel fileName="Rubberband" screenName="RubberBand" toolTip="Rubberband Selection"/>
                <Panel fileName="Pick" screenName="Pick" toolTip="Show Info for Picked Item"/>
                <Panel fileName="SynchroCursors" screenName="SyncCursors" toolTip="Synchronised Cursors"/>
                <Panel fileName="FishEye" screenName="FishEye" toolTip="FishEye Transformation"/>
                <Panel fileName="Skew" screenName="Skew" toolTip="Skew Interaction"/>
                <Panel fileName="ScaleCopy" screenName="Scale" toolTip="Scale Interaction"/>
            </InteractionControl>
            <InteractionControl availableInDemoMode="YES" defaultInDemoMode="NO" projectionName="XZ">
                <Panel fileName="ZMR" screenName="ZMR" toolTip="Zoom/Move/Rotate"/>
                <Panel fileName="Rubberband" screenName="RubberBand" toolTip="Rubberband Selection"/>
                <Panel fileName="Pick" screenName="Pick" toolTip="Show Info for Picked Item"/>
                <Panel fileName="SynchroCursors" screenName="SyncCursors" toolTip="Synchronised Cursors"/>
                <Panel fileName="FishEye" screenName="FishEye" toolTip="FishEye Transformation"/>
                <Panel fileName="ScaleCopy" screenName="Scale" toolTip="Scale Interaction"/>
            </InteractionControl>
            <InteractionControl availableInDemoMode="YES" defaultInDemoMode="NO" projectionName="YZ">
                <Panel fileName="ZMR" screenName="ZMR" toolTip="Zoom/Move/Rotate"/>
                <Panel fileName="Rubberband" screenName="RubberBand" toolTip="Rubberband Selection"/>
                <Panel fileName="Pick" screenName="Pick" toolTip="Show Info for Picked Item"/>
                <Panel fileName="SynchroCursors" screenName="SyncCursors" toolTip="Synchronised Cursors"/>
                <Panel fileName="FishEye" screenName="FishEye" toolTip="FishEye Transformation"/>
                <Panel fileName="ScaleCopy" screenName="Scale" toolTip="Scale Interaction"/>
            </InteractionControl>
            <InteractionControl availableInDemoMode="YES" defaultInDemoMode="NO" projectionName="FZ">
                <Panel fileName="ZMR" screenName="ZMR" toolTip="Zoom/Move/Rotate"/>
                <Panel fileName="Rubberband" screenName="RubberBand" toolTip="Rubberband Selection"/>
                <Panel fileName="Pick" screenName="Pick" toolTip="Show Info for Picked Item"/>
                <Panel fileName="SynchroCursors" screenName="SyncCursors" toolTip="Synchronised Cursors"/>
                <Panel fileName="FishEye" screenName="FishEye" toolTip="FishEye Transformation"/>
                <Panel fileName="Skew" screenName="Skew" toolTip="Skew Interaction"/>
                <Panel fileName="ScaleCopy" screenName="Scale" toolTip="Scale Interaction"/>
            </InteractionControl>
            <InteractionControl availableInDemoMode="YES" defaultInDemoMode="NO" projectionName="FR">
                <Panel fileName="ZMR" screenName="ZMR" toolTip="Zoom/Move/Rotate"/>
                <Panel fileName="RubberbandYX" screenName="RubberBand" toolTip="Rubberband Selection"/>
                <Panel fileName="Pick" screenName="Pick" toolTip="Show Info for Picked Item"/>
                <Panel fileName="SynchroCursors" screenName="SyncCursors" toolTip="Synchronised Cursors"/>
                <Panel fileName="FishEye" screenName="FishEye" toolTip="FishEye Transformation"/>
                <Panel fileName="Skew" screenName="Skew" toolTip="Skew Interaction"/>
                <Panel fileName="ScaleCopy" screenName="Scale" toolTip="Scale Interaction"/>
            </InteractionControl>
            <InteractionControl availableInDemoMode="YES" defaultInDemoMode="YES" projectionName="VP">
                <Panel fileName="VPSelection" screenName="RubberBand" toolTip="Rubberband Selection"/>
                <Panel fileName="Pick" screenName="Pick" toolTip="Show Info for Picked Item"/>
                <Panel fileName="ZMR" screenName="ZMR" toolTip="Zoom/Move/Rotate"/>
                <Panel fileName="SynchroCursors" screenName="SyncCursors" toolTip="Synchronised Cursors"/>
                <Panel fileName="ScaleCopy" screenName="Scale" toolTip="Scale Interaction"/>
            </InteractionControl>
            <InteractionControl availableInDemoMode="NO" defaultInDemoMode="NO" projectionName="3D">
                <Panel fileName="ZMR" screenName="ZMR" toolTip="Zoom/Move/Rotate"/>
                <Panel fileName="VPSelection" screenName="RubberBand" toolTip="Rubberband Selection"/>
                <Panel fileName="Pick" screenName="Pick" toolTip="Show Info for Picked Item"/>
                <Panel fileName="FishEye" screenName="FishEye" toolTip="FishEye Transformation"/>
                <Panel fileName="SynchroCursors" screenName="SyncCursors" toolTip="Synchronised Cursors"/>
                <Panel fileName="ScaleCopy" screenName="Scale" toolTip="Scale Interaction"/>
            </InteractionControl>
            <InteractionControl availableInDemoMode="NO" defaultInDemoMode="NO" projectionName="3DBox">
                <Panel fileName="3DBox" screenName="ZR" toolTip="Zoom/Rotate"/>
                <!-- temporarily remove "Pick" interaction for 3DBox until it is implemented
                <Panel fileName="Pick" screenName="Pick" toolTip="Show Info for Picked Item"/>
                -->
            </InteractionControl>
            <InteractionControl availableInDemoMode="YES" defaultInDemoMode="NO" projectionName="LegoPlot">
                <Panel fileName="ZMR" screenName="ZMR" toolTip="Zoom/Move/Rotate"/>
                <Panel fileName="SynchroCursors" screenName="SyncCursors" toolTip="Synchronised Cursors"/>
                <!-- temporarily remove "Pick" interaction for Lego until it is implemented
                <Panel fileName="Pick" screenName="Pick" toolTip="Show Info for Picked Item"/>
                -->
            </InteractionControl>
            <InteractionControl availableInDemoMode="NO" defaultInDemoMode="NO" projectionName="TrackResidual">
                <Panel fileName="Pick" screenName="Pick" toolTip="Show Info for Picked Item"/>
            </InteractionControl>
            <InteractionControl availableInDemoMode="YES" defaultInDemoMode="NO" projectionName="N3D">
                <Panel fileName="NZMR" screenName="Rotate" toolTip="Zoom/Move/Rotate"/>
            </InteractionControl>
            <InteractionControl availableInDemoMode="YES" defaultInDemoMode="NO" projectionName="NYX">
            </InteractionControl>
            <InteractionControl availableInDemoMode="YES" defaultInDemoMode="NO" projectionName="NPhysics">
                <Panel fileName="NZMR" screenName="Rotate" toolTip="Zoom/Move/Rotate"/>
            </InteractionControl>
            <InteractionControl availableInDemoMode="YES" defaultInDemoMode="NO" projectionName="EventInfo">
            </InteractionControl>
        </Interactions>
        <Canvas aspectRatio="NaN" startupLayout="SQUARE">
            <UsedWindow group="Data" name="1" projection="YX"/>
            <UsedWindow group="Data" name="2" projection="FR"/>
            <UsedWindow group="Data" name="3" projection="FZ"/>
            <UsedWindow group="Data" name="4" projection="YZ"/>
            <UsedWindow group="Data" name="5" projection="RZ"/>
            <UsedWindow group="Data" name="6" projection="VP"/>
            <UsedWindow group="Data" name="7" projection="XZ"/>
            <UsedWindow group="Data" name="8" projection="VP"/>
            <UsedWindow group="Data" name="9" projection="LegoPlot"/>
            <UsedWindow group="Data" name="L" projection="YX"/>
            <UsedWindow group="Data" name="M" projection="RZ"/>
            <UsedWindow group="Data" name="R" projection="VP"/>
            <UsedWindow group="Data" name="U" projection="YX"/>
            <UsedWindow group="Data" name="C" projection="FR"/>
            <UsedWindow group="Data" name="D" projection="RZ"/>
            <UsedWindow group="Data" name="E" projection="FZ"/>
            <UsedWindow group="Data" name="S" projection="YX"/>
            <UsedWindow group="Data" name="W" projection="YX"/>
            <UsedWindow group="Data" name="B" projection="RZ"/>
            <Layout name="LANDSCAPE" startup="S36" startupWindow="S">
                <Window hPos="0" height="1" name="1" vPos="0" width="1"/>
                <Window hPos="1" height="1" name="2" vPos="0" width="1"/>
                <Window hPos="2" height="1" name="3" vPos="0" width="1"/>
                <Window hPos="0" height="1" name="4" vPos="1" width="1"/>
                <Window hPos="1" height="1" name="5" vPos="1" width="1"/>
                <Window hPos="2" height="1" name="6" vPos="1" width="1"/>
                <Window hPos="0" height="2" name="L" vPos="0" width="1"/>
